/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
import {base} from './../UIBaseView';
import UIBaseView = base.UIBaseView;
UIBaseView.init();
var REG: Function = Laya.ClassUtils.regClass;
export module ui.view {
    export class DebugViewUI extends UIBaseView {
		public list:Laya.List;
		public btnBox:Laya.Box;
		public btnClear:Laya.Button;
		public btnClose:Laya.Button;
		public imput_Num:Laya.TextInput;
		public btn_makeSure:Laya.Button;
		public btn_server:Laya.Button;
		public input_money:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/DebugView");
        }
    }
    REG("ui.view.DebugViewUI",DebugViewUI);
    export class EliGameUI extends UIBaseView {
		public bg:Laya.Image;
		public board:Laya.Box;
		public tarScore:Laya.Label;
		public nowScore:Laya.Label;
		public lv:Laya.Label;
		public returnBtn:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/EliGame");
        }
    }
    REG("ui.view.EliGameUI",EliGameUI);
    export class FailViewUI extends UIBaseView {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/FailView");
        }
    }
    REG("ui.view.FailViewUI",FailViewUI);
    export class HomeViewUI extends UIBaseView {
		public btnStart:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/HomeView");
        }
    }
    REG("ui.view.HomeViewUI",HomeViewUI);
    export class LoadingViewUI extends UIBaseView {
		public bar:Laya.ProgressBar;
		public txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/LoadingView");
        }
    }
    REG("ui.view.LoadingViewUI",LoadingViewUI);
    export class ResultViewUI extends UIBaseView {
		public lblGold:Laya.Label;
		public imgGold:Laya.Image;
		public lblLevel:Laya.Label;
		public lblAddGold:Laya.Label;
		public flyGold:any;
		public imgClose:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/ResultView");
        }
    }
    REG("ui.view.ResultViewUI",ResultViewUI);
}