/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
import {base} from './../UIBaseView';
import UIBaseView = base.UIBaseView;
UIBaseView.init();
var REG: Function = Laya.ClassUtils.regClass;
export module ui.view {
    export class DebugViewUI extends UIBaseView {
		public list:Laya.List;
		public btnBox:Laya.Box;
		public btnClear:Laya.Button;
		public btnClose:Laya.Button;
		public imput_Num:Laya.TextInput;
		public btn_makeSure:Laya.Button;
		public btn_server:Laya.Button;
		public input_money:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/DebugView");
        }
    }
    REG("ui.view.DebugViewUI",DebugViewUI);
    export class EliGameUI extends UIBaseView {
		public bg:Laya.Image;
		public board:Laya.Box;
		public tarScore:Laya.Label;
		public nowScore:Laya.Label;
		public lv:Laya.Label;
		public returnBtn:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/EliGame");
        }
    }
    REG("ui.view.EliGameUI",EliGameUI);
    export class FailViewUI extends UIBaseView {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/FailView");
        }
    }
    REG("ui.view.FailViewUI",FailViewUI);
    export class GoBangUI extends Laya.UIBaseView {
		public chessboard:Laya.Box;
		public winTip:Laya.Label;
		public gameTime:Laya.Label;
		public startOver:Laya.Button;
		public returnBtn:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/GoBang");
        }
    }
    REG("ui.view.GoBangUI",GoBangUI);
    export class HomeViewUI extends UIBaseView {
		public eliBtn:Laya.Button;
		public pickBtn:Laya.Button;
		public chessBtn:Laya.Button;
		public numGameBtn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/HomeView");
        }
    }
    REG("ui.view.HomeViewUI",HomeViewUI);
    export class LoadingViewUI extends UIBaseView {
		public bar:Laya.ProgressBar;
		public txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/LoadingView");
        }
    }
    REG("ui.view.LoadingViewUI",LoadingViewUI);
    export class NumGameViewUI extends Laya.UIBaseView {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/NumGameView");
        }
    }
    REG("ui.view.NumGameViewUI",NumGameViewUI);
    export class pickBallViewUI extends Laya.UIBaseView {
		public returnBtn:Laya.Box;
		public ballView:Laya.Panel;
		public plank:Laya.Sprite;
		public tarScore:Laya.Label;
		public timeBar:Laya.ProgressBar;
		public bmask:Laya.Image;
		public scoreBox:Laya.Box;
		public finalScore:Laya.Label;
		public restart:Laya.Button;
		public exitLobby:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/pickBallView");
        }
    }
    REG("ui.view.pickBallViewUI",pickBallViewUI);
    export class ResultViewUI extends UIBaseView {
		public lblGold:Laya.Label;
		public imgGold:Laya.Image;
		public lblLevel:Laya.Label;
		public lblAddGold:Laya.Label;
		public flyGold:any;
		public imgClose:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/ResultView");
        }
    }
    REG("ui.view.ResultViewUI",ResultViewUI);
}