/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import DebugView from "./script/DebugView"
import EliGameScene from "./script/eliminateGame/EliGameScene"
import FailView from "./script/FailView"
import HomeView from "./script/HomeView"
import LoadingView from "./script/LoadingView"
import ResultView from "./script/ResultView"
import FlyGold from "./core/ui/FlyGold"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1280;
    static height:number=720;
    static scaleMode:string="exactfit";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="view/EliGame.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/DebugView.ts",DebugView);
        reg("script/eliminateGame/EliGameScene.ts",EliGameScene);
        reg("script/FailView.ts",FailView);
        reg("script/HomeView.ts",HomeView);
        reg("script/LoadingView.ts",LoadingView);
        reg("script/ResultView.ts",ResultView);
        reg("core/ui/FlyGold.ts",FlyGold);
    }
}
GameConfig.init();