/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import DebugView from "./script/DebugView"
import EliGameScene from "./script/eliminateGame/EliGameScene"
import FailView from "./script/FailView"
import GoBangScene from "./script/goBangGame/GoBangScene"
import HomeView from "./script/HomeView"
import KlotskiView from "./script/klotski/KlotskiView"
import LoadingView from "./script/LoadingView"
import NumGameScene from "./script/2048Game/NumGameScene"
import PickBallGame from "./script/pickBall/PickBallGame"
import ResultView from "./script/ResultView"
import FlyGold from "./core/ui/FlyGold"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="showall";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="view/DebugView.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/DebugView.ts",DebugView);
        reg("script/eliminateGame/EliGameScene.ts",EliGameScene);
        reg("script/FailView.ts",FailView);
        reg("script/goBangGame/GoBangScene.ts",GoBangScene);
        reg("script/HomeView.ts",HomeView);
        reg("script/klotski/KlotskiView.ts",KlotskiView);
        reg("script/LoadingView.ts",LoadingView);
        reg("script/2048Game/NumGameScene.ts",NumGameScene);
        reg("script/pickBall/PickBallGame.ts",PickBallGame);
        reg("script/ResultView.ts",ResultView);
        reg("core/ui/FlyGold.ts",FlyGold);
    }
}
GameConfig.init();